<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="robots" content="noindex">
        <title>YouTube Audio Downloader</title>
        <link rel="stylesheet" type="text/css" href="styles/main.css">
    </head>
    <body>
        <h1>YouTube Audio Downloader</h1>
        <p><?php echo $message; ?></p>
        <p><a href="/">Click here to enter another url</a></p>
    </body>
</html>
