<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="robots" content="noindex">
        <title>YouTube Audio Downloader</title>
        <link rel="stylesheet" type="text/css" href="styles/main.css">
    </head>
    <body>
        <h1>YouTube Audio Downloader</h1>
        <form method="post" action="/">
            <label for="url">URL:</label>&nbsp;<input type="text" id="url" name="url" size="60" placeholder="for example, https://www.youtube.com/watch?v=dQw4w9WgXcQ">
            <input type="submit" value="Submit">
        </form>
    </body>
</html>
